export const INITIAL_VISIBLE_MOVIES_COUNT_LARGE = 12;
export const INITIAL_VISIBLE_MOVIES_COUNT_MEDIUM = 8;
export const INITIAL_VISIBLE_MOVIES_COUNT_SMALL = 5;

export const ADDITIONAL_MOVIES_COUNT_LARGE = 3;
export const ADDITIONAL_MOVIES_COUNT_MEDIUM = 2;
export const ADDITIONAL_MOVIES_COUNT_SMALL = 2;
export const ADDITIONAL_MOVIES_COUNT_ZERO = 0;

export const DURATION_THRESHOLD = 40;
export const SCREEN_WIDTH_LARGE = 1280;
export const SCREEN_WIDTH_MEDIUM = 768;